// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiperuBackend.Data;

#nullable disable

namespace SiperuBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210061140_SyncModelSchema")]
    partial class SyncModelSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SiperuBackend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 2, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Rapat Himpunan",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            StudentName = "Ahmad Fauzi"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 2, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Workshop Programming",
                            RoomId = 3,
                            StartTime = new DateTime(2026, 2, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            StudentName = "Siti Nurhaliza"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2026, 2, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Seminar Mahasiswa",
                            RoomId = 4,
                            StartTime = new DateTime(2026, 2, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            StudentName = "Budi Santoso"
                        });
                });

            modelBuilder.Entity("SiperuBackend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang Kelas Lantai 1",
                            IsAvailable = true,
                            Name = "C-101"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang Kelas Lantai 1",
                            IsAvailable = true,
                            Name = "C-102"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab dengan 25 PC",
                            IsAvailable = true,
                            Name = "Lab Komputer 1"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aula untuk acara besar",
                            IsAvailable = true,
                            Name = "Aula"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 15,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang untuk rapat kecil",
                            IsAvailable = true,
                            Name = "Ruang Rapat"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab Multimedia",
                            IsAvailable = true,
                            Name = "Lab Komputer 2"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Untuk seminar dan presentasi",
                            IsAvailable = true,
                            Name = "Ruang Seminar"
                        });
                });

            modelBuilder.Entity("SiperuBackend.Models.Booking", b =>
                {
                    b.HasOne("SiperuBackend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
